---
- hosts: all
  remote_user: root

  tasks:
   - name: Run apt-get update
     sudo: true
     apt: update_cache=yes 

   - name: Install python pip
     sudo: true
     apt: pkg=python-pip state=installed update_cache=true

   - name: Install git
     sudo: true
     apt: pkg=git state=installed update_cache=true

   - name: cloning repo
     sudo: false
     command: git clone https://github.com/amritbhanu/VCL.git
