---
- hosts: all

  tasks:
   - name: Run apt-get update
     sudo: true
     apt: update_cache=yes

   - name: Install python-matplotlib 
     sudo: true
     apt: pkg=python-matplotlib state=installed update_cache=true

   - name: Install wget
     sudo: true
     apt: pkg=wget state=installed update_cache=true

   - name: Install git
     sudo: true
     apt: pkg=git state=installed update_cache=true

   - name: cloning repo
     sudo: false
     command: git clone https://github.com/amritbhanu/VCL.git

   - name: create spark dir
     file: path=/spark state=directory mode=0755

   - name: download sources
     sudo: true
     get_url: url=http://ftp.wayne.edu/apache//spark/spark-1.4.1/spark-1.4.1-bin-hadoop2.6.tgz dest=/spark/

   - name: Unarchive Spark download
     sudo: true
     unarchive: src=/spark/spark-1.4.1-bin-hadoop2.6.tgz dest=/spark copy=no

   - name: Move spark dir to spark_latest
     sudo: true
     command: mv /spark/spark-1.4.1-bin-hadoop2.6 /spark/spark_latest

   - name: Install JRE to set JAVA_HOME
     sudo: true
     apt: name=openjdk-7-jre state=present

